### ISSUE TITLE
 US14: SET UP COMMON FACILITIES MANAGEMENT

### ISSUE THREAD

**Issue by JRB958** [THE-390-Team/THE-390#30]
As Brian (condo management company manager) , I want to set up and manage common facilities that require reservations, such as a sky lounge and spa fitness, to organize and offer these amenities efficiently to condo owners and rental users.

**Tasks**

- [ ] Design and implement a MongoDB schema to store information about common facilities, including names, descriptions, and available reservation time slots.
- [ ] Create Django RESTful API endpoints for managing (creating, updating, deleting) the details of these facilities.
- [ ] Develop a React component for condo management companies to manage the setup and details of common facilities.
- [ ] Implement input validation to ensure the integrity of the data being entered for each facility.
- [ ] Establish access control measures to ensure that only authorized personnel can manage these details.
